<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.475">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ing. Agr. Ivone Humacata">

<title>DISEÑO EXPERIMENTAL</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#diseño-en-parcelas-divididas" id="toc-diseño-en-parcelas-divididas" class="nav-link active" data-scroll-target="#diseño-en-parcelas-divididas"><span class="toc-section-number">1</span>  DISEÑO EN PARCELAS DIVIDIDAS</a>
  <ul class="collapse">
  <li><a href="#objetivos-de-aprendizaje" id="toc-objetivos-de-aprendizaje" class="nav-link" data-scroll-target="#objetivos-de-aprendizaje"><span class="toc-section-number">1.1</span>  OBJETIVOS DE APRENDIZAJE</a></li>
  <li><a href="#introduccion" id="toc-introduccion" class="nav-link" data-scroll-target="#introduccion"><span class="toc-section-number">1.2</span>  INTRODUCCION</a></li>
  <li><a href="#ejemplo-9-variedades-y-fechas-de-siembra" id="toc-ejemplo-9-variedades-y-fechas-de-siembra" class="nav-link" data-scroll-target="#ejemplo-9-variedades-y-fechas-de-siembra"><span class="toc-section-number">1.3</span>  EJEMPLO 9 ~ VARIEDADES Y FECHAS DE SIEMBRA</a>
  <ul class="collapse">
  <li><a href="#objetivo" id="toc-objetivo" class="nav-link" data-scroll-target="#objetivo"><span class="toc-section-number">1.3.1</span>  OBJETIVO</a></li>
  <li><a href="#aleatorizacion" id="toc-aleatorizacion" class="nav-link" data-scroll-target="#aleatorizacion"><span class="toc-section-number">1.3.2</span>  ALEATORIZACION</a></li>
  <li><a href="#unidades-experimentales" id="toc-unidades-experimentales" class="nav-link" data-scroll-target="#unidades-experimentales"><span class="toc-section-number">1.3.3</span>  UNIDADES EXPERIMENTALES</a></li>
  <li><a href="#unidades-de-observacion" id="toc-unidades-de-observacion" class="nav-link" data-scroll-target="#unidades-de-observacion"><span class="toc-section-number">1.3.4</span>  UNIDADES DE OBSERVACION</a></li>
  <li><a href="#variable-respuesta" id="toc-variable-respuesta" class="nav-link" data-scroll-target="#variable-respuesta"><span class="toc-section-number">1.3.5</span>  VARIABLE RESPUESTA</a></li>
  <li><a href="#diseño" id="toc-diseño" class="nav-link" data-scroll-target="#diseño"><span class="toc-section-number">1.3.6</span>  DISEÑO</a></li>
  <li><a href="#cargar-la-base-de-datos" id="toc-cargar-la-base-de-datos" class="nav-link" data-scroll-target="#cargar-la-base-de-datos"><span class="toc-section-number">1.3.7</span>  CARGAR LA BASE DE DATOS</a></li>
  <li><a href="#analisis-exploratorio" id="toc-analisis-exploratorio" class="nav-link" data-scroll-target="#analisis-exploratorio"><span class="toc-section-number">1.3.8</span>  ANALISIS EXPLORATORIO</a></li>
  <li><a href="#modelo-matematico" id="toc-modelo-matematico" class="nav-link" data-scroll-target="#modelo-matematico"><span class="toc-section-number">1.3.9</span>  MODELO MATEMATICO</a></li>
  <li><a href="#hipotesis-de-analisis" id="toc-hipotesis-de-analisis" class="nav-link" data-scroll-target="#hipotesis-de-analisis"><span class="toc-section-number">1.3.10</span>  HIPOTESIS DE ANALISIS</a></li>
  <li><a href="#anova" id="toc-anova" class="nav-link" data-scroll-target="#anova"><span class="toc-section-number">1.3.11</span>  ANOVA</a></li>
  <li><a href="#verificacion-de-los-supuestos-del-modelo" id="toc-verificacion-de-los-supuestos-del-modelo" class="nav-link" data-scroll-target="#verificacion-de-los-supuestos-del-modelo"><span class="toc-section-number">1.3.12</span>  VERIFICACION DE LOS SUPUESTOS DEL MODELO</a></li>
  <li><a href="#conclusiones-del-modelo-planteado" id="toc-conclusiones-del-modelo-planteado" class="nav-link" data-scroll-target="#conclusiones-del-modelo-planteado"><span class="toc-section-number">1.3.13</span>  CONCLUSIONES DEL MODELO PLANTEADO</a></li>
  <li><a href="#confiabilidad-del-modelo" id="toc-confiabilidad-del-modelo" class="nav-link" data-scroll-target="#confiabilidad-del-modelo"><span class="toc-section-number">1.3.14</span>  CONFIABILIDAD DEL MODELO</a></li>
  <li><a href="#test-de-tukey" id="toc-test-de-tukey" class="nav-link" data-scroll-target="#test-de-tukey"><span class="toc-section-number">1.3.15</span>  TEST DE TUKEY</a></li>
  </ul></li>
  <li><a href="#recursos-recomendados" id="toc-recursos-recomendados" class="nav-link" data-scroll-target="#recursos-recomendados"><span class="toc-section-number">1.4</span>  RECURSOS RECOMENDADOS</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">DISEÑO EXPERIMENTAL</h1>
<p class="subtitle lead">Facultad de Ciencias Agrarias - UNJu. Año 2023</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ing. Agr. Ivone Humacata </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="diseño-en-parcelas-divididas" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> DISEÑO EN PARCELAS DIVIDIDAS</h1>
<section id="objetivos-de-aprendizaje" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="objetivos-de-aprendizaje"><span class="header-section-number">1.1</span> OBJETIVOS DE APRENDIZAJE</h2>
<div style="text-align: justify">

<ol type="1">
<li><p>Plantear adecuadamente los componentes del modelo matemático de un diseño en parcelas divididas aplicado a un DCA y a un DBCA.</p></li>
<li><p>Desarrollar destrezas técnicas en el manejo de software estadístico para el análisis de datos experimentales.</p></li>
<li><p>Realizar el analisis estadistico de un diseño en parcelas divididas para un DCA y un DBCA. Interpretar y comunicar correctamente los resultados del analísis estadístico.</p></li>
<li><p>Evaluar la confiabilidad de los resultados experimentales.</p></li>
</ol>
</div></section>
<section id="introduccion" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="introduccion"><span class="header-section-number">1.2</span> INTRODUCCION</h2>
<div style="text-align: justify">

<p>Este tipo de diseño fue desarrollado en 1925 por el matemático Ronald Fisher para su uso en experimentos agrícolas. El diseño de parcela dividida se usa comúnmente cuando hay dos o más factores de interés, donde un factor se aplica a unidades experimentales completas (parcelas principales) y el otro factor se aplica a subunidades más pequeñas dentro de las parcelas principales (subparcelas). La principal ventaja del diseño de parcelas divididas es su capacidad para asignar recursos de manera eficiente mientras se acomodan las limitaciones prácticas del experimento.</p>
<p>Los diseños de parcelas divididas tienen dos ventajas sobre los diseños completamente al azar:</p>
<ul>
<li><p>Costo: dado que uno de los factores no tiene que cambiarse para cada parcela dividida, esto significa que este tipo de diseno tiende a ser más barato de llevar a cabo en la práctica.</p></li>
<li><p>Eficiencia: conduce a un aumento en la precision de las estimaciones para todos los efectos de los factores excepto para los efectos principales de la parcela completa.</p></li>
</ul>
<p><em>Regla General:</em></p>
<ul>
<li><p><em>Un factor es facil de cambiar o variar.</em></p></li>
<li><p><em>Un factor es dificil de cambiar o variar.</em></p></li>
</ul>
</div></section>
<section id="ejemplo-9-variedades-y-fechas-de-siembra" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="ejemplo-9-variedades-y-fechas-de-siembra"><span class="header-section-number">1.3</span> EJEMPLO 9 ~ VARIEDADES Y FECHAS DE SIEMBRA</h2>
<div style="text-align: justify">

<p>Se realizó un experimento para comparar el rendimiento de dos variedades de arroz (A y B) sembradas en dos parcelas diferentes. Dentro de las parcelas se hicieron subparcelas para comparar el efecto de tres fechas de siembra sobre la producción de arroz y se consideraron tres bloques, teniendo en cuenta la pendiente del suelo. Los datos se presentan a continuación<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>:</p>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<tbody>
<tr class="odd">
<td>Bloque I</td>
<td></td>
<td></td>
<td></td>
<td>Bloque II</td>
<td></td>
<td></td>
<td></td>
<td>Bloque III</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Variedad A</td>
<td></td>
<td>VariedadB</td>
<td></td>
<td>Variedad A</td>
<td></td>
<td>Variedad B</td>
<td></td>
<td>Variedad A</td>
<td></td>
<td>Variedad B</td>
<td></td>
</tr>
<tr class="odd">
<td>F1</td>
<td>5.0</td>
<td>F3</td>
<td>6.5</td>
<td>F1</td>
<td>5.4</td>
<td>F2</td>
<td>6.5</td>
<td>F3</td>
<td>6.6</td>
<td>F1</td>
<td>6.5</td>
</tr>
<tr class="even">
<td>F2</td>
<td>5.3</td>
<td>F1</td>
<td>6.7</td>
<td>F3</td>
<td>6.4</td>
<td>F3</td>
<td>6.6</td>
<td>F1</td>
<td>5.6</td>
<td>F2</td>
<td>6.6</td>
</tr>
<tr class="odd">
<td>F3</td>
<td>6.8</td>
<td>F2</td>
<td>6.8</td>
<td>F2</td>
<td>5.9</td>
<td>F1</td>
<td>6.8</td>
<td>F2</td>
<td>6.9</td>
<td>F3</td>
<td>6.8</td>
</tr>
</tbody>
</table>
<section id="objetivo" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="objetivo"><span class="header-section-number">1.3.1</span> OBJETIVO</h3>
<p>Comparar el rendimiento de dos variedades de arroz en distintas fechas de siembra.</p>
</section>
<section id="aleatorizacion" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="aleatorizacion"><span class="header-section-number">1.3.2</span> ALEATORIZACION</h3>
<ul>
<li><p>En un primer paso, se aleatorizó las parcelas principales a los bloques.</p></li>
<li><p>En un segundo paso, se aleatorizó las subparcelas dentro de cada parcela.</p></li>
</ul>
</section>
<section id="unidades-experimentales" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="unidades-experimentales"><span class="header-section-number">1.3.3</span> UNIDADES EXPERIMENTALES</h3>
<p>En este diseño se tiene dos tipos de unidades experimentales:</p>
<p>Para las parcelas las unidades experimentales son las áreas de tierra donde se siembran las variedades de arroz.</p>
<p>Para las subparcelas son las subáreas dentro de las parcelas donde se asignan las fechas de siembra.</p>
</section>
<section id="unidades-de-observacion" class="level3" data-number="1.3.4">
<h3 data-number="1.3.4" class="anchored" data-anchor-id="unidades-de-observacion"><span class="header-section-number">1.3.4</span> UNIDADES DE OBSERVACION</h3>
<p>Cada planta de donde se obtiene el valor del rendimiento para una combinación variedad-fecha.</p>
</section>
<section id="variable-respuesta" class="level3" data-number="1.3.5">
<h3 data-number="1.3.5" class="anchored" data-anchor-id="variable-respuesta"><span class="header-section-number">1.3.5</span> VARIABLE RESPUESTA</h3>
<p>Rendimiento de arroz.</p>
</section>
<section id="diseño" class="level3" data-number="1.3.6">
<h3 data-number="1.3.6" class="anchored" data-anchor-id="diseño"><span class="header-section-number">1.3.6</span> DISEÑO</h3>
<p>Diseño en Parcelas Divididas aplicado a un DBCA.</p>
<p>Parcela o parcela principal (PP): variedades de arroz (A y B).</p>
<p>Subparcela o parcela secundaria (SP): fechas de siembra (F1, F2 y F3).</p>
<p>Bloques: tipos de pendientes en el suelo (I, II, III).</p>
</section>
<section id="cargar-la-base-de-datos" class="level3" data-number="1.3.7">
<h3 data-number="1.3.7" class="anchored" data-anchor-id="cargar-la-base-de-datos"><span class="header-section-number">1.3.7</span> CARGAR LA BASE DE DATOS</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"arroz_DPD.xlsx"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>datos<span class="sc">$</span>bloque <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(datos<span class="sc">$</span>bloque)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>datos<span class="sc">$</span>fecha<span class="ot">&lt;-</span> <span class="fu">as.factor</span> (datos<span class="sc">$</span>fecha)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>datos<span class="sc">$</span>var<span class="ot">&lt;-</span> <span class="fu">as.factor</span> (datos<span class="sc">$</span>var)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [18 × 4] (S3: tbl_df/tbl/data.frame)
 $ bloque: Factor w/ 3 levels "I","II","III": 1 1 1 1 1 1 2 2 2 2 ...
 $ fecha : Factor w/ 3 levels "F1","F2","F3": 1 2 3 3 1 2 1 3 2 2 ...
 $ var   : Factor w/ 2 levels "A","B": 1 1 1 2 2 2 1 1 1 2 ...
 $ rend  : num [1:18] 5 5.3 6.8 6.5 6.7 6.8 5.4 6.4 5.9 6.5 ...</code></pre>
</div>
</div>
</section>
<section id="analisis-exploratorio" class="level3" data-number="1.3.8">
<h3 data-number="1.3.8" class="anchored" data-anchor-id="analisis-exploratorio"><span class="header-section-number">1.3.8</span> ANALISIS EXPLORATORIO</h3>
<p><strong>Gráfico de cajas</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> var, <span class="at">y =</span> rend, <span class="at">fill =</span> fecha)) <span class="sc">+</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Variedad de arroz"</span>, <span class="at">y =</span> <span class="st">"Rendimiento"</span>, <span class="at">fill =</span> <span class="st">"Fecha de siembra"</span>) <span class="sc">+</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Variedades de arroz segun fecha de siembra"</span>) <span class="sc">+</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Medidas de resumen</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># solicitar medidas de variedades</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">%&gt;%</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(var) <span class="sc">%&gt;%</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">minimo =</span> <span class="fu">round</span>(<span class="fu">min</span>(rend), <span class="dv">2</span>),</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">media =</span> <span class="fu">round</span>(<span class="fu">mean</span>(rend), <span class="dv">2</span>),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">desvio =</span> <span class="fu">round</span>(<span class="fu">sd</span>(rend), <span class="dv">2</span>),</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">asimetria =</span> <span class="fu">round</span>(<span class="fu">skewness</span>(rend), <span class="dv">2</span>),</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">mediana =</span> <span class="fu">round</span>(<span class="fu">median</span>(rend), <span class="dv">2</span>),</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">CV =</span> <span class="fu">round</span>((desvio<span class="sc">/</span>media<span class="sc">*</span><span class="dv">100</span>),<span class="dv">2</span>),</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">maximo =</span> <span class="fu">round</span>(<span class="fu">max</span>(rend), <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 8
  var   minimo media desvio asimetria mediana    CV maximo
  &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1 A        5    5.99   0.71      0.01     5.9 11.8     6.9
2 B        6.5  6.64   0.13      0.13     6.6  1.96    6.8</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># solicitar medidas de resumen para fechas de siembra</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>datos <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(fecha) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">minimo =</span> <span class="fu">round</span>(<span class="fu">min</span>(rend), <span class="dv">2</span>),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">media =</span> <span class="fu">round</span>(<span class="fu">mean</span>(rend), <span class="dv">2</span>),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">desvio =</span> <span class="fu">round</span>(<span class="fu">sd</span>(rend), <span class="dv">2</span>),</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">asimetria =</span> <span class="fu">round</span>(<span class="fu">skewness</span>(rend), <span class="dv">2</span>),</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">mediana =</span> <span class="fu">round</span>(<span class="fu">median</span>(rend), <span class="dv">2</span>),</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">CV =</span> <span class="fu">round</span>((desvio<span class="sc">/</span>media<span class="sc">*</span><span class="dv">100</span>),<span class="dv">2</span>),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">maximo =</span> <span class="fu">round</span>(<span class="fu">max</span>(rend), <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 8
  fecha minimo media desvio asimetria mediana    CV maximo
  &lt;fct&gt;  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
1 F1       5    6      0.76     -0.15    6.05 12.7     6.8
2 F2       5.3  6.33   0.62     -0.83    6.55  9.79    6.9
3 F3       6.4  6.62   0.16      0.03    6.6   2.42    6.8</code></pre>
</div>
</div>
<p><strong>Grafico de interacción</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  datos<span class="sc">$</span>var,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  datos<span class="sc">$</span>fecha,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  datos<span class="sc">$</span>rend,</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"rendimiento"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"var"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">trace.label =</span> <span class="st">"fecha"</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  datos<span class="sc">$</span>fecha,</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  datos<span class="sc">$</span>var,</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  datos<span class="sc">$</span>rend,</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"rendimiento"</span>,</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"fecha"</span>,</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">trace.label =</span> <span class="st">"var"</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="modelo-matematico" class="level3" data-number="1.3.9">
<h3 data-number="1.3.9" class="anchored" data-anchor-id="modelo-matematico"><span class="header-section-number">1.3.9</span> MODELO MATEMATICO</h3>
<p>El modelo matemático para parcela dividida aplicado a un DBCA es:</p>
<p><span class="math inline">y_{ijk}= \mu + \alpha_i + \delta_k + \eta_{(i)k} + \beta_j + (\alpha\beta)_{ij} + \epsilon_{ijk}</span></p>
<p>Con<br>
i=A, B<br>
j=F1, F2, F3<br>
k= I, II, III<br>
</p>
<p>Donde:</p>
<p><span class="math inline">y_{ijk}</span> es el rendimiento observado.</p>
<p><span class="math inline">\mu</span> es la media general.<br>
<span class="math inline">\alpha_i</span> es el efecto del i-ésimo nivel del factor A o parcela (variedad).<br>
<span class="math inline">\delta_k</span> es el efecto del bloque k (pendiente)<br>
<span class="math inline">\eta_{(i)k}</span> es el error aleatorio de la parcela. (tambien llamado error A). Siendo <span class="math inline">\eta_{(i)k} \sim N(0, \sigma^2)</span><br>
<span class="math inline">\beta_j</span> es el efecto del j-ésimo nivel del factor B o subparcela (fecha de siembra).<br>
<span class="math inline">\alpha\beta_{ij}</span> es la interaccion entre los dos factores (parcela-subparcela).<br>
<span class="math inline">\epsilon_{ijk}</span> es el error aleatorio de la subparcela (tambien llamado error B). Siendo <span class="math inline">\epsilon_{ijk} \sim N(0, \sigma^2)</span></p>
</section>
<section id="hipotesis-de-analisis" class="level3" data-number="1.3.10">
<h3 data-number="1.3.10" class="anchored" data-anchor-id="hipotesis-de-analisis"><span class="header-section-number">1.3.10</span> HIPOTESIS DE ANALISIS</h3>
<p>Hipotesis a plantear:</p>
<ul>
<li>Parcelas principales</li>
</ul>
<p><span class="math inline">H_0</span>: No existen diferencias entre los efectos de la parcela principal vs.&nbsp;<span class="math inline">H_1</span>: Existen diferencias entre los efectos de la parcela principal.</p>
<ul>
<li>Sub parcelas</li>
</ul>
<p><span class="math inline">H_0</span>: No existen diferencias entre los efectos de la subparcela vs. <span class="math inline">H_1</span>: Existen diferencias entre los efectos de la subparcela.</p>
<ul>
<li>Interacción PP : SP</li>
</ul>
<p><span class="math inline">H_0</span>: No existen diferencias entre los efectos de la interacción parcela:subparcela vs.&nbsp;<span class="math inline">H_1</span>: Existen diferencias entre los efectos de la interacción parcela:subparcela</p>
</section>
<section id="anova" class="level3" data-number="1.3.11">
<h3 data-number="1.3.11" class="anchored" data-anchor-id="anova"><span class="header-section-number">1.3.11</span> ANOVA</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># aplicar el modelo planteado</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>modelo<span class="ot">=</span><span class="fu">aov</span>(rend<span class="sc">~</span>bloque<span class="sc">+</span>var<span class="sc">*</span>fecha<span class="sc">+</span><span class="fu">Error</span>(bloque<span class="sc">:</span>var),datos)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: bloque:var
          Df Sum Sq Mean Sq F value Pr(&gt;F)  
bloque     2 0.3233  0.1617   0.848  0.541  
var        1 1.9339  1.9339  10.149  0.086 .
Residuals  2 0.3811  0.1906                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Error: Within
          Df Sum Sq Mean Sq F value Pr(&gt;F)  
fecha      2  1.143  0.5717   4.533 0.0483 *
var:fecha  2  1.274  0.6372   5.053 0.0381 *
Residuals  8  1.009  0.1261                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(agricolae)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sp.plot</span>(datos<span class="sc">$</span>bloque, datos<span class="sc">$</span>var, datos<span class="sc">$</span>fecha, datos<span class="sc">$</span>rend)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
ANALYSIS SPLIT PLOT:  datos$rend 
Class level information

datos$var   :  A B 
datos$fecha     :  F1 F2 F3 
datos$bloque    :  I II III 

Number of observations:  18 

Analysis of Variance Table

Response: datos$rend
                      Df  Sum Sq Mean Sq F value  Pr(&gt;F)  
datos$bloque           2 0.32333 0.16167     NaN     NaN  
datos$var              1 1.93389 1.93389 10.1487 0.08601 .
Ea                     2 0.38111 0.19056     NaN     NaN  
datos$fecha            2 1.14333 0.57167  4.5330 0.04829 *
datos$var:datos$fecha  2 1.27444 0.63722  5.0529 0.03812 *
Eb                     8 1.00889 0.12611     NaN     NaN  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

cv(a) = 6.9 %, cv(b) = 5.6 %, Mean = 6.316667 </code></pre>
</div>
</div>
<p><em>Interaccion parcela-subparcela</em></p>
<p>Con un un p-valor menor a <span class="math inline">\alpha</span> se rechaza la Ho.</p>
<p><em>Subparcela</em></p>
<p>Con un p-valor menor a<span class="math inline">\alpha</span> se rechaza la Ho.</p>
<p><em>Parcela</em></p>
<p>Con un un p-valor mayor a <span class="math inline">\alpha</span> no se rechaza la Ho.</p>
<p><strong>Conclusión</strong></p>
<p>Existen diferencias signicativas entre los efectos de parcela-subparcela (variedad-fecha de siembra). Es necesario validar el modelo para que la conclusión sea válida.</p>
</section>
<section id="verificacion-de-los-supuestos-del-modelo" class="level3" data-number="1.3.12">
<h3 data-number="1.3.12" class="anchored" data-anchor-id="verificacion-de-los-supuestos-del-modelo"><span class="header-section-number">1.3.12</span> VERIFICACION DE LOS SUPUESTOS DEL MODELO</h3>
<p>Los supuestos que se comprobaran son homogeneidad de varianzas y normalidad de residuos.</p>
<p><strong>Graficamente</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># normalidad de residuos </span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dae)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>residuos<span class="ot">=</span><span class="fu">residuals.aovlist</span>(modelo)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(residuos);<span class="fu">qqline</span>(residuos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># homogenenidad de varianzas</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>pred<span class="ot">=</span><span class="fu">fitted.values</span>(modelo)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>st.resid<span class="ot">=</span><span class="fu">scale</span>(residuos)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(pred,st.resid)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Supuesto de normalidad. Test de Shapiro Wilks</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="fu">resid</span>(modelo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  resid(modelo)
W = 0.93438, p-value = 0.2317</code></pre>
</div>
</div>
<p>El supuesto de normalidad se cumple.</p>
<p><strong>Homogeneidad de Varianzas ~ Test de Levenne</strong></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># crear el vector tratamiento</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>trat<span class="ot">=</span><span class="fu">interaction</span>(datos<span class="sc">$</span>var,datos<span class="sc">$</span>fecha)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(<span class="fu">resid</span>(modelo),trat,<span class="at">center =</span> mean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = mean)
      Df F value Pr(&gt;F)
group  5  1.9747 0.1551
      12               </code></pre>
</div>
</div>
<p>El supuesto de homogeneidad de varianzas se cumple.</p>
</section>
<section id="conclusiones-del-modelo-planteado" class="level3" data-number="1.3.13">
<h3 data-number="1.3.13" class="anchored" data-anchor-id="conclusiones-del-modelo-planteado"><span class="header-section-number">1.3.13</span> CONCLUSIONES DEL MODELO PLANTEADO</h3>
<p>Se concluye que los efectos de la interaccion variedad-fecha de siembra son significativos en el rendimiento de arroz (<span class="math inline">F_{(2, 8)}=5.05, p-value =0.03812</span>) a un nivel de significacion de <span class="math inline">\alpha = 0.05</span>. Se realizará pruebas de comparacion de medias post hoc para saber cual es el mejor tratamiento.</p>
<p>Nota: realizamos la conclusión final en base a la interacción porque este diseño busca estudiar esos efectos como objetivo principal.</p>
</section>
<section id="confiabilidad-del-modelo" class="level3" data-number="1.3.14">
<h3 data-number="1.3.14" class="anchored" data-anchor-id="confiabilidad-del-modelo"><span class="header-section-number">1.3.14</span> CONFIABILIDAD DEL MODELO</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>modelo<span class="ot">=</span><span class="fu">aov</span>(rend<span class="sc">~</span>bloque<span class="sc">+</span>var<span class="sc">*</span>fecha<span class="sc">+</span><span class="fu">Error</span>(bloque<span class="sc">:</span>var),datos)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
Error: bloque:var
          Df Sum Sq Mean Sq F value Pr(&gt;F)  
bloque     2 0.3233  0.1617   0.848  0.541  
var        1 1.9339  1.9339  10.149  0.086 .
Residuals  2 0.3811  0.1906                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Error: Within
          Df Sum Sq Mean Sq F value Pr(&gt;F)  
fecha      2  1.143  0.5717   4.533 0.0483 *
var:fecha  2  1.274  0.6372   5.053 0.0381 *
Residuals  8  1.009  0.1261                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>SCEE <span class="ot">=</span> <span class="fl">0.3811+1.009</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>SCBloq <span class="ot">=</span> <span class="fl">0.3233</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>SCVar <span class="ot">=</span> <span class="fl">1.9339</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>SCFecha <span class="ot">=</span> <span class="fl">1.143</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>SCFechaVar <span class="ot">=</span> <span class="fl">1.274</span></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>r2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">-</span>(SCEE<span class="sc">/</span>(SCBloq<span class="sc">+</span>SCVar<span class="sc">+</span>SCFecha<span class="sc">+</span>SCFechaVar<span class="sc">+</span>SCEE))); r2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7707732</code></pre>
</div>
</div>
<p>Con un CV bajo podemos decir que el modelo es adecuado y con un <span class="math inline">r^2</span> igual a 0.77 tiene buen poder explicativo.</p>
</section>
<section id="test-de-tukey" class="level3" data-number="1.3.15">
<h3 data-number="1.3.15" class="anchored" data-anchor-id="test-de-tukey"><span class="header-section-number">1.3.15</span> TEST DE TUKEY</h3>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(agricolae)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>HSD_test <span class="ot">=</span> <span class="fu">with</span>(datos, <span class="fu">HSD.test</span>(rend, var<span class="sc">:</span>fecha, <span class="at">DFerror =</span> <span class="dv">8</span>, <span class="at">MSerror =</span> <span class="fl">0.126</span>))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>HSD_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>$statistics
  MSerror Df     Mean       CV      MSD
    0.126  8 6.316667 5.619495 1.058951

$parameters
   test    name.t ntr StudentizedRange alpha
  Tukey var:fecha   6         5.167152  0.05

$means
         rend       std r Min Max  Q25 Q50  Q75
A:F1 5.333333 0.3055050 3 5.0 5.6 5.20 5.4 5.50
A:F2 6.033333 0.8082904 3 5.3 6.9 5.60 5.9 6.40
A:F3 6.600000 0.2000000 3 6.4 6.8 6.50 6.6 6.70
B:F1 6.666667 0.1527525 3 6.5 6.8 6.60 6.7 6.75
B:F2 6.633333 0.1527525 3 6.5 6.8 6.55 6.6 6.70
B:F3 6.633333 0.1527525 3 6.5 6.8 6.55 6.6 6.70

$comparison
NULL

$groups
         rend groups
B:F1 6.666667      a
B:F2 6.633333      a
B:F3 6.633333      a
A:F3 6.600000      a
A:F2 6.033333     ab
A:F1 5.333333      b

attr(,"class")
[1] "group"</code></pre>
</div>
</div>
<p>No se presentan diferecias estadisticas entre las distintas fechas de siembra para la variedad B y la variedad A-fecha de siembra 3, siendo que éstas combinaciones presentan las mayores medias de rendimiento. La variedad A con las fechas de siembra 1 y 2, presentan las menores medias y se diferencian estadísticamente de las demás.</p>
</section>
</div></section>
<section id="recursos-recomendados" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="recursos-recomendados"><span class="header-section-number">1.4</span> RECURSOS RECOMENDADOS</h2>
<p><strong>Bibliografia</strong></p>
<p>Lawson, J. (2014).&nbsp;<em>Design and Analysis of Experiments with R</em>&nbsp;(Vol. 115). CRC press. Cap 8. Pags. 307-350. Disponible en: https://elearning.unite.it/pluginfile.php/221606/mod_resource/content/1/BookDOEwithR.pdf</p>
<p>Kuehl, R. (2001). Diseño de experimentos. 2da Edición. Pags. 481-469.</p>
<p>Melo, O., López, L. y Melo, S. (2020). Diseño de Experimentos. Pags. 518-524. Bogotá, Colombia</p>
<p>Quinteros, H. (1997). Diseño Experimental. Facultad de Ciencias Agrarias, Universidad Nacional de Jujuy. Pags. 110-126.</p>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Tomado y adaptado de Melo et al.&nbsp;(2020) Diseño de Experimentos. Bogota, Colombia.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>